version: '2.1'

# Address: http://172.29.111.95:8080

volumes:
  wwwroot:
  keys:
  db:
  ldap:
  ldap_slapd:

services:
  develop:
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/UTC"
      DB_HOST: "db"
      DB_Database: "DevDB"
      DB_User: "root"
      DB_Password: "testPW"
      LDAP_ORGANISATION: "nuv.systems"
      LDAP_DOMAIN: "nuv.systems"
      LDAP_BASE_DN: "dc=nuv,dc=systems"
      LDAP_ADMIN_PASSWORD: "eT*671uvbJ#toK$I"
    ports:
      - "8080:80"
      - "8081:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - wwwroot:/app/wwwroot
      - keys:/root/.aspnet
    restart: unless-stopped
    links:          
      - db
      - ldap
    depends_on:
      - db
      - ldap
  
  db:
    image: mysql:8.0.31-debian
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'testPW'
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "8082:3306"
  
  ldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "nuv.systems"
      LDAP_DOMAIN: "nuv.systems"
      LDAP_BASE_DN: "dc=nuv,dc=systems"
      LDAP_ADMIN_PASSWORD: "eT*671uvbJ#toK$I"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "false"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: 'binddn="cn=admin,cn=config" bindmethod=simple credentials="$$LDAP_CONFIG_PASSWORD" searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical'
      #LDAP_REPLICATION_DB_SYNCPROV: 'binddn="cn=admin,$$LDAP_BASE_DN" bindmethod=simple credentials="$$LDAP_ADMIN_PASSWORD" searchbase="$$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical'
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
    tty: true
    stdin_open: true
    volumes:
      - ldap:/var/lib/ldap
      - ldap_slapd:/etc/ldap/slapd.d
    ports:
      - "8083:389"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    links:
      - ldap
    depends_on:
      - ldap
    ports:
      - "8084:80"